INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (1002, 'aria', 'Get AWS Certified', CURRENT_DATE, false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1003, 'alex', 'Learn Microsoft Azure', CURRENT_DATE, false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1004, 'ben', 'Learn Google Cloud', CURRENT_DATE, false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1005, 'rose', 'Learn Machine Learning', CURRENT_DATE, false);
